import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import ReactQueryProvider from '@/utils/provider';
import NavBar from '@/components/navbar';
import { navbarJson, navbarLinkJson } from '@/constants/navbar';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'My Task',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>
          <AntdRegistry>
            <NavBar json={navbarJson} jsonLink={navbarLinkJson} />
            {children}
          </AntdRegistry>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
